<a href="https://colab.research.google.com/github/2303a510g5/B15_PDS_10g5/blob/main/LAB_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 3D NumPy array (3x3x3) to simulate RGB image
image = np.array([
    [[123, 50, 200],
     [34, 210, 89],
     [255, 180, 75]],

    [[45, 60, 90],
     [220, 130, 40],
     [10, 240, 180]],

    [[100, 200, 150],
     [60, 90, 120],
     [80, 160, 220]]
], dtype=np.uint8)

In [2]:
print("Original Image (3x3x3):\n", image)

Original Image (3x3x3):
 [[[123  50 200]
  [ 34 210  89]
  [255 180  75]]

 [[ 45  60  90]
  [220 130  40]
  [ 10 240 180]]

 [[100 200 150]
  [ 60  90 120]
  [ 80 160 220]]]


In [3]:
red_layer = image[:, :, 0]
green_layer = image[:, :, 1]
blue_layer = image[:, :, 2]

print("\nRed Channel:\n", red_layer)
print("\nGreen Channel:\n", green_layer)
print("\nBlue Channel:\n", blue_layer)


Red Channel:
 [[123  34 255]
 [ 45 220  10]
 [100  60  80]]

Green Channel:
 [[ 50 210 180]
 [ 60 130 240]
 [200  90 160]]

Blue Channel:
 [[200  89  75]
 [ 90  40 180]
 [150 120 220]]


In [4]:
avg_red = np.mean(red_layer)
avg_green = np.mean(green_layer)
avg_blue = np.mean(blue_layer)

print("\nAverage Intensities:")
print(f"Red: {avg_red:.2f}, Green: {avg_green:.2f}, Blue: {avg_blue:.2f}")


Average Intensities:
Red: 103.00, Green: 146.67, Blue: 129.33


In [5]:
brightened = np.clip(image + 50, 0, 255)
print("\nBrightened Image:\n", brightened)


Brightened Image:
 [[[173 100 250]
  [ 84   4 139]
  [ 49 230 125]]

 [[ 95 110 140]
  [ 14 180  90]
  [ 60  34 230]]

 [[150 250 200]
  [110 140 170]
  [130 210  14]]]


In [6]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# 1D Array
b = np.array([10, 20, 30])

# Broadcasting (2D + 1D)
C = A + b
print("2D + 1D Broadcasting:\n", C)

2D + 1D Broadcasting:
 [[11 22 33]
 [14 25 36]]


In [7]:
D = np.ones((2,3,4)) * 5
scalar = 10
E = D + scalar
print("\n3D + scalar Broadcasting:\n", E)


3D + scalar Broadcasting:
 [[[15. 15. 15. 15.]
  [15. 15. 15. 15.]
  [15. 15. 15. 15.]]

 [[15. 15. 15. 15.]
  [15. 15. 15. 15.]
  [15. 15. 15. 15.]]]


In [8]:
b2 = np.array([1,2,3])
expanded = b2[:, np.newaxis]
print("\nShape Transformation Example:")
print("Original b2.shape:", b2.shape)
print("Expanded b2.shape:", expanded.shape)


Shape Transformation Example:
Original b2.shape: (3,)
Expanded b2.shape: (3, 1)


In [11]:
X = np.ones((2,3))
# Changed Y to have shape (3,) to be compatible with X for broadcasting
Y = np.ones((3,))
Z = X + Y
print("\n2D + 1D Broadcasting (Fixed Example):")
print("X shape:", X.shape)
print("Y shape:", Y.shape)
print("Result Z:\n", Z)


2D + 1D Broadcasting (Fixed Example):
X shape: (2, 3)
Y shape: (3,)
Result Z:
 [[2. 2. 2.]
 [2. 2. 2.]]
